name = "5-weekly"
author = "Ignas"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d47eb23270c58e310fa17ca69239df2a169d9b609cb27a85364655ebd39f01d3"

[versions]
forge = "65.1.1"
minecraft = "26.2"
